// K2 Events/Angular/k2_events-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'm1_components-app';
}

<h1>Meine Bestellungen</h1>

<app-order artikel="Schweizer Bergkäse" preis="3.99" menge="5"></app-order>

// K3 Bedingtes Rendering/Vue/k3_bedingtesRendering-app/src/App.vue
<template>
  <h1>Meine Bestellungen</h1>
  <Order artikel="Schweizer Bergkäse" preis="3.99" menge="5"></Order>
  <Order artikel="Frankreicher Brocciu" preis="0" menge="500"></Order>
  <Order artikel="Italienischer Parmesankäse" preis="-2" menge="30"></Order>
</template>

<script>
import Order from './components/Order.vue'

export default {
  name: 'App',
  components: {
    Order
  }
}
</script>
