// K4 Routing und Navigation/React/k4_routingNavigation-app/src/App.js
import AppRouter from "./AppRouter";

export default function App() {
  return (
    <div className="App">
      <nav>
        <div>
          <ul>
            <li>
              <a href="/orders"> Meine Bestellungen </a>
            </li>
            <li>
              <a href="/account"> Mein Konto </a>
            </li>
          </ul>
        </div>
      </nav>
      <AppRouter />
    </div>
  );
}

// K5 Asynchroner Datenabruf/Angular/k5_asynchronerDatenabruf-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'm4_routingAndNavigation-app';
}

<nav>
    <div>
      <ul>
          <li><a routerLink="/orders-component"  
            routerLinkActive="active" ariaCurrentWhenActive="page"> Meine Bestellungen </a></li>
          <li><a routerLink="/account-component" 
            routerLinkActive="active" ariaCurrentWhenActive="page"> Mein Konto </a></li>
            <li><a routerLink="/recommendations-component" 
              routerLinkActive="active" ariaCurrentWhenActive="page"> Empfehlungen </a></li>
      </ul>
  </div>
</nav>
<router-outlet></router-outlet>
