// K2 Events/Angular/k2_events-app/src/app/order/order.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.css']
})
export class OrderComponent {
  @Input('artikel') artikel = '';
  @Input('preis') preis = '';
  @Input('menge') menge = '';

  waehrung : string = "€";

  public getWaehrungsanzeige() : string {
    return this.waehrung == "€" ? "In $ anzeigen" : "In € anzeigen";
  }

  public getGesamtPreis() : string {
    return (Number(this.preis)* Number(this.menge)).toFixed(2);
  }

  public waehrungUmschalten(){
    if (this.waehrung == "€")
    {
      this.preis = (Number(this.preis) * 1.03).toFixed(2);
      this.waehrung = "$"
    }
    else
    {
      this.preis = (Number(this.preis) / 1.03).toFixed(2);
      this.waehrung = "€"
    }
  }
} 


<p>Artikel: {{artikel}} </p>
<p>Menge: {{menge}} Stück</p>
<p>Preis: {{preis}}{{waehrung}}</p>
<p>Gesamt: {{getGesamtPreis()}}{{waehrung}}</p>

<button (click)="waehrungUmschalten()">
    {{getWaehrungsanzeige()}}
</button>

// K5 Asynchroner Datenabruf/React/k5_asynchronerDatenabruf-app/src/order/Order.js
import React from "react";

class Order extends React.Component {

    constructor(props) {
        super(props);
        this.state = { waehrung: "€", preis: props.preis };
    
        // This binding is necessary to make `this` work in the callback
        this.waehrungUmschalten = this.waehrungUmschalten.bind(this);
      }

    getWaehrungsanzeige()  {
      return this.state.waehrung === "€" ? "In $ anzeigen" : "In € anzeigen";
    }
  
    waehrungUmschalten(){
      if (this.state.waehrung === "€")
      {
        this.setState({waehrung: "$", preis: (Number(this.state.preis) * 1.03).toFixed(2)});

      }
      else
      {
        this.setState({waehrung: "€", preis: (Number(this.state.preis) / 1.03).toFixed(2)});
      }
    }

    getGesamtPreis()  {
        return (Number(this.state.preis)* Number(this.props.menge)).toFixed(2);
    }

    render()
    {
      if (Number(this.state.preis) <= 0 || Number(this.props.menge) <= 0)
      {
          return null;
      }

       return (
            <div>
               <p>Artikel: {this.props.artikel} </p>
               <p>Menge: {this.props.menge} Stück</p>
               <p>Preis: {this.state.preis}{this.state.waehrung}</p>
               <p>Gesamt: {this.getGesamtPreis()}{this.state.waehrung}</p>

               <button onClick={this.waehrungUmschalten}>
                   {this.getWaehrungsanzeige()}
               </button>
            </div>         
       )
   }
  }

  export default Order;
