// K1 Components/React/k1_components-app/src/Order/Order.js
import React from "react";

class Order extends React.Component {

     render()
     {
        return (
             <div>
                 <p>Artikel: {this.props.artikel} </p>
                 <p>Menge: {this.props.menge} Stück</p>
                 <p>Preis: {this.props.preis}€</p>
                 <p>Gesamt: {this.getGesamtPreis()}€</p>
             </div>  
        )
    }
    
    getGesamtPreis()  {
        return (Number(this.props.preis)* Number(this.props.menge)).toFixed(2);
    }
  }

  export default Order;

// K1 Components/Vue/k1_components-app/src/components/Order.vue
<template>
    <p> Artikel: {{artikel}} </p>
    <p> Menge: {{menge}} Stück</p>
    <p>Preis: {{preis}}€</p>
    <p>Gesamt: {{getGesamtPreis()}}€</p>
</template>

<script>
export default {
  name: 'myOrder',
  props: {
    preis: String,
    artikel: String,
    menge: String
  },
  methods: {
     getGesamtPreis(){
        return (Number(this.preis)* Number(this.menge)).toFixed(2);
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
