// K5 Asynchroner Datenabruf/React/k5_asynchronerDatenabruf-app/src/App.js
import AppRouter from "./AppRouter";

export default function App() {
  return (
    <div className="App">
      <nav>
        <div>
          <ul>
            <li><a href="/orders"> Meine Bestellungen </a></li>
             <li><a href="/account"> Mein Konto </a></li>
             <li><a href="/recommendations"> Empfehlungen </a></li>
          </ul>
        </div>
      </nav>
      <AppRouter/>
    </div>
  );
}

// K6 Globale Zustandsverwaltung/Angular/k6_globaleZustandsverwaltung-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})




export class AppComponent {
  title = 'm4_routingAndNavigation-app';
  count: number = 0;

  constructor(private store: Store<{count: number}>) {
    this.store.select("count").subscribe((data) => {
      this.count = data
    })
   }
}



<h1>{{this.count}} Artikel im Warenkorb</h1>
<nav>
    <div>
      <ul>
          <li><a routerLink="/orders-component"  
            routerLinkActive="active" ariaCurrentWhenActive="page"> Meine Bestellungen </a></li>
          <li><a routerLink="/account-component" 
            routerLinkActive="active" ariaCurrentWhenActive="page"> Mein Konto </a></li>
            <li><a routerLink="/recommendations-component" 
              routerLinkActive="active" ariaCurrentWhenActive="page"> Empfehlungen </a></li>
      </ul>
  </div>
</nav>
<router-outlet></router-outlet>
