// K7 Animationen/Vue/k7_animations-app/src/components/Recommendations.vue
  <template>
<div>
    <div v-if="error">
        <h1>Empfehlungen</h1>
         Error: {{error.message}}
    </div>
    <div v-else-if="isLoaded === false">
        <h1>Meine Bestellungen</h1>Bitte warten...  
    </div>
    <div v-else>
        <h1>Empfehlungen</h1>
         <ol>
                  <li v-for="item in items" v-bind:key="item.id" >
                    <p><strong>{{item.description}}</strong> </p>
                    <p>Bewertung: {{item.rating}}/5</p>
                    <p>Preis: {{item.price}}€</p>
                    <p>Versand: {{item.deliveryCost <= 0 ? 'Kostenlos' : item.deliveryCost+'€'}}</p>
                    <p>{{item.summary}}</p>
                        <button @click="inDenWarenkorb()">
                        In den Warenkorb
                      </button>
                  </li>
              </ol>
    </div>
</div>
</template>
  <script>

import { store } from './store';

export default {
    
  name: 'myRecommendations',

  data() {
    return {
        isLoaded :  false,
        items : null,
        error : null 
    };
  },
  created() {
     fetch("https://localhost:7281/Recommendation")
          .then(res => res.json())
          .then(
            (result) => {
                this.isLoaded = true;
                this.items = result
            },
            (error) => {
                this.isLoaded = true;
                this.error = error;
            }
          )
  },
  methods: {
      inDenWarenkorb() {
        store.count = store.count + 1;
      }
  }
}
</script>

// K7 Animationen/React/k7_animations-app/src/recommendations/recommendations.js
import React from "react";
import UserContext from "../UserContext/userContext";
import { motion } from "framer-motion";

class Recommendations extends React.Component {
  static contextType = UserContext;

  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      items: [],
    };
    // This binding is necessary to make `this` work in the callback
    this.inDenWarenkorb = this.inDenWarenkorb.bind(this);
  }

  inDenWarenkorb() {
    const { value, setValue } = this.context;
    setValue(Number(value) + 1);
  }

  componentDidMount() {
    fetch("https://localhost:7281/Recommendation")
      .then((res) => res.json())
      .then(
        (result) => {
          this.setState({
            isLoaded: true,
            items: result,
          });
        },
        (error) => {
          this.setState({
            isLoaded: true,
            error,
          });
        }
      );
  }

  render() {
    const { error, isLoaded, items } = this.state;
    if (error) {
      return (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <h1>Empfehlungen</h1>
          Error: {error.message}
        </motion.div>
      );
    } else if (!isLoaded) {
      return (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <h1>Empfehlungen</h1>Bitte warten...
        </motion.div>
      );
    } else {
      return (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <h1>Empfehlungen</h1>
          <ol>
            {items.map((item) => (
              <li key={item.id}>
                <p>
                  <strong>{item.description}</strong>{" "}
                </p>
                <p>Bewertung: {item.rating}/5</p>
                <p>Preis: {item.price}€</p>

                <p>
                  Versand:{" "}
                  {item.deliveryCost <= 0
                    ? "Kostenlos"
                    : item.deliveryCost + "€"}
                </p>
                <p>{item.summary}</p>

                <button onClick={this.inDenWarenkorb}>In den Warenkorb</button>
              </li>
            ))}
          </ol>
        </motion.div>
      );
    }
  }
}
export default Recommendations;
