// K1 Components/Angular/k1_components-app/src/app/order/order.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.css']
})
export class OrderComponent {

  @Input('artikel') artikel = '';
  @Input('preis') preis = '';
  @Input('menge') menge = '';

  public getGesamtPreis() : string {
    return (Number(this.preis)* Number(this.menge)).toFixed(2);
  }
}

<p> Artikel: {{artikel}} </p>
<p> Menge: {{menge}} Stück</p>
<p>Preis: {{preis}}€</p>
<p>Gesamt: {{getGesamtPreis()}}€</p>

// K1 Components/React/k1_components-app/src/Order/Order.js
import React from "react";

class Order extends React.Component {

     render()
     {
        return (
             <div>
                 <p>Artikel: {this.props.artikel} </p>
                 <p>Menge: {this.props.menge} Stück</p>
                 <p>Preis: {this.props.preis}€</p>
                 <p>Gesamt: {this.getGesamtPreis()}€</p>
             </div>  
        )
    }
    
    getGesamtPreis()  {
        return (Number(this.props.preis)* Number(this.props.menge)).toFixed(2);
    }
  }

  export default Order;
